### ISSUE TITLE
API

### ISSUE THREAD

**Issue by yoshuawuyts** [yoshuawuyts/merry#1]
### examples

``` js
// asset serving
const browserify = require('browserify')
const bankai = require('bankai')
const merry = require('merry')

const assets = bankai()
const app = merry()
app.router([
  ['/', assets.html()],
  ['/bundle.js', assets.js(browserify)],
  ['/bundle.css', assets.css()]
])
app.start()
```

``` js
// API
const merry = require('merry')
const pull = require('pull')

const app = merry()

app.router([
  ['/routes/foo', {
    post: (http$) => pull(http$) // echo request back to response
  }]
])

app.start()
```

``` js
// expose to cli
const browserify = require('browserify')
const bankai = require('bankai')
const merry = require('merry')

if (module.parent) module.exports = createApp
else createApp({ port: 8080 })

function createApp (config) {
  const assets = bankai()
  const app = merry(config)
  app.router([
    ['/', assets.html()],
    ['/bundle.js', assets.js(browserify)],
    ['/bundle.css', assets.css()]
  ])
  app.start()
}
```
### features
- merry should be able to take `process.argv` to read config from command line
- merry should be able to take a config object to read config from inline
- `require('merry/log')` should provide a `bole` instance
- merry should configure `bole` to print to stdout. Defaults to `debug` level
- merry should log by default
- merry should default to `pull-stream`, but can detect and read from `Node streams`
### questions
- should we include a dispatcher?

**Comment by davidmarkclements** [comment]
For the array tuples, what we're looking at is a key and a value - so objects should do? You could still support tuples for 3+ sibling values?

**Comment by davidmarkclements** [comment]
Also cc @mcollina

**Comment by yoshuawuyts** [comment]
@davidmarkclements well, but the idea is that you can nest paths to create a sitemap-like structure like so:
```js
// asset serving
const browserify = require('browserify')
const bankai = require('bankai')
const merry = require('merry')

const assets = bankai()
const app = merry()
app.router([
  ['/auth', require('./service-auth')],
  ['/404', require('./service-404')],
  ['/foo', require('./service-foo'), [
    ['/boop', require('./service-boop')],
    ['/bar', require('./service-bar'), [
      ['/:beep', require('./service-beep')]
    ]]
  ]]
])
app.start()
```
Same as in `choo` :sparkles:

**Comment by yoshuawuyts** [comment]
```js
// server side rendering of choo apps
const render = require('server-render')
const merry = require('merry')
const client = require('./client')

const app = merry()
app.use(render((route) => client.toString(route))) // expects a string to be returned statically
app.start()
```

**Comment by davidmarkclements** [comment]
Convenience - `merry.ssr => (c) => (r) => c.toString(r)`

```js
const render = require('server-render')
const merry = require('merry')
const server = merry.ssr(require('./client'))

const app = merry()
app.use(render(server))
app.start()
```

or `const ssr = require('merry-ssr')`

**Comment by yoshuawuyts** [comment]
@davidmarkclements Yeah I see what you're getting at, but I think one thing to be careful about is tying `choo` and `merry` together too deeply; e.g. the `.toString()` method is specific to `choo` - having a generic callback that expects a string to be returned works better I reckon :sparkles:

I'm actually building out the `server-render` package right now: [readme](https://gist.github.com/yoshuawuyts/1a271740b22599d5a5101b5fc9e85336) :rocket:

**Comment by davidmarkclements** [comment]
I guess it's the age old tension between explicitness and terseness

It's pretty awesome what you're doing here, because it requires minimum code, 

```
function render(routeToStringFn) {
  return http.createServer((req, res) => res.end(routeToStringFn(req.url)))
}
```

1. What about methods (i.e. POST requests) etc. 
2. Is there a case for returning a stream instead of a string?
3. Use of closures like this makes for powerful APIs, but not best for perf- and this *will* be a hot path

**Comment by yoshuawuyts** [comment]
ahh, yeah so what I was thinking was to create an index of buffers that can be used to match and pipe results through instantly; which should be better for perf I reckon :sparkles:
```js
const hyperstream = require('hyperstream')
const index = require('simple-html-index')
const assert = require('assert')
const xtend = require('xtend')
const pump = require('pump')
const bl = require('bl')

const defaultOpts = {
  entry: 'bundle.js',
  css: 'bundle.css',
  favicon: true
}

module.exports = serverRender

// HTML server rendering middleware
// (obj?, fn(str) -> str) -> fn(obj, obj, fn)
function serverRender (opts, routes, handler) {
  if (!handler) {
    handler = routes
    routes = opts
    opts = {}
  }

  const cache = {}

  assert.equal(typeof opts, 'object', 'server-render: opts should be a function')
  assert.equal(typeof routes, 'object', 'server-render: routes should be a function')
  assert.equal(typeof handler, 'function', 'server-render: handler should be a function')

  routes.routes.forEach(function (route) {
    const buf = cacheRoute(route)
    cache[route] = buf
  })

  const defaultRoute = cacheRoute(routes.default)
  const indexOpts = xtend(defaultOpts, opts)

  // call middlewarereadme
  // (obj, obj, fn) -> null
  return function (req, res, next) {
    res.setHeader('Content-Type', 'text/html; charset=utf-8')

    if (cache[req.url]) {
      cache[req.url].duplicate().pipe(res)
    } else {
      res.statusCode = 404
      defaultRoute.duplicate().pipe(res)
    }
  }

  // cache a route in the cache
  // str -> Buffer
  function cacheRoute (route) {
    const html = handler(route)
    const hs = hyperstream({ 'body': { _appendHtml: html } })
    const buf = bl()
    pump(index(indexOpts), hs, buf)
    return buf
  }
}
```

**Comment by yoshuawuyts** [comment]
@davidmarkclements released it :grin: https://github.com/yoshuawuyts/server-render

**Comment by davidmarkclements** [comment]
no pub'd to npm though? npm inst of v1.0.0 has index.js from initial commit

**Comment by yoshuawuyts** [comment]
@davidmarkclements published `v1.0.1` :tada:

**Comment by mcollina** [comment]
good job! :)

**Comment by sotojuan** [comment]
API lookin' good!

**Comment by yoshuawuyts** [comment]
switched from syc retursn to a callback that takes an error or stream - easier to reason about and probably faster (less stream constructors). Thanks @mafintosh for the suggestion. Closing now; thanks everyone for chiming in! :grin:
