### ISSUE TITLE
app.log is not defined

### ISSUE THREAD

**Issue by ebuckthal** [yoshuawuyts/merry#24]
v3 doesn't expose app.log as the examples suggest. 

index.js:
```js
var merry = require('merry')
var app = merry()

app.log.info('look at the logs!')
```
outputs:
```
app.log.info('look at the logs!')
       ^

TypeError: Cannot read property 'info' of undefined
```
It appears it is only exposed via `app._log`. The easy fix would be to just rename `._log` to `.log`, but I'm not sure what the intention is.

**Comment by yoshuawuyts** [comment]
thanks for reporting, you're right - fixed in `v3.0.2`
