### ISSUE TITLE
create a cute pretty printer

### ISSUE THREAD

**Issue by yoshuawuyts** [yoshuawuyts/merry#27]
e.g. https://github.com/mattdesl/garnish but for `pino` - we could probs simplify the code a lot lot lot (:

**Comment by nichoth** [comment]
ps, pino already has one :) `var log = pino({level: 'info'}, pino.pretty())`

**Comment by yoshuawuyts** [comment]
haha, yeah we talked to the pino folks about this and got the green light
to build an even prettier one - even squatting on what might be a top 1%
amazing cool npm name that goes down in cool npm naming history rn. It's
gonna be so gooood (we're not actually squatting tho - it's like, we got
the best _idea_ for a name hah)

**Comment by lrlna** [comment]
just jumping in to agree that it is *the* best name; tbh i would even say
top 0.5% of all npm package names

**Comment by yoshuawuyts** [comment]
0.25% perhaps even but what do I know

**Comment by lrlna** [comment]
if you like [pino-coladas](https://github.com/lrlna/pino-colada) and getting caught in the raiiiiiiin 🍹 🍍 

(released in 4.6.0 ✨)
