### ISSUE TITLE
error handling

### ISSUE THREAD

**Issue by lrlna** [yoshuawuyts/merry#30]
continue discussion abt handling errors in merry here

**Comment by yoshuawuyts** [comment]
From #20:

---

> Well couple of things

> 1. The `boom` module has some great concepts when it comes to handling and propagating HTTP errors to HTTP clients (mu-error wraps boom) - `boom` objects are ultimately instances of `Error` object - in particular 500+ errors messages are automatically redacted - mu-error adds a dev option to re-expose them. 
> 2. Error serialization - when you stringify an Error object you don't get the message or the stack (although with `pino` you do, so for most cases this may already be solved) - mu-error solves this in a performant way by piggybacking on the JSON stringify loop (essentially using toJSON) 
> 3. Conversion of error-like objects to legit. Error objects without copying properties - this can be a nice way to enforce an error creation pattern (that all errors are instances of Error) whilst providing a  convenient API for adding props to Errors - e.g. instead of 

```js
var err = new Error('not found')
err.code = 404
```

> You could do:

```js
var err = merry.error({message: 'not found', code: 404})
```

> And this would morph the input object into an Error object (avoiding property copying is much better perf wise)
