### ISSUE TITLE
include a json schema parser

### ISSUE THREAD

**Issue by lrlna** [yoshuawuyts/merry#39]
merry should handle json schema and be able to parse it ^_^

-- 
idea is also to be able to validate json schema and its data, which would be especially useful when testing application code instead of writing mocks.

**Comment by yoshuawuyts** [comment]
e.g. include a `middleware` and a `parser` :sparkles:

**Comment by yoshuawuyts** [comment]
I'm thinking syntax for bundled-in middleware should be `merry.middleware.something` which can then be passed into `merry.middleware`
