### ISSUE TITLE
Possible breakage on Node 7

### ISSUE THREAD

**Issue by yoshuawuyts** [yoshuawuyts/merry#53]
Noticed tests were failing on an app I'm building; not sure what's the cause but we should investigate what changed in core. 
<img width="942" alt="screen shot 2017-01-15 at 03 30 01" src="https://cloud.githubusercontent.com/assets/2467194/21959821/86d6c1a4-dad3-11e6-952a-c845d98f352e.png">

**Comment by lrlna** [comment]
ugh :(

i am not that familiar with circle output -- does the build give you any other info we can work?

**Comment by yoshuawuyts** [comment]
Oh this is Travis (:

**Comment by lrlna** [comment]
Clearly don't know Travis either lolololol 😂

**Comment by yoshuawuyts** [comment]
hah, yeah so this is fine (: just don't use `null` as the first arg in `.listen()`
