### ISSUE TITLE
question: log process error events

### ISSUE THREAD

**Issue by nichoth** [yoshuawuyts/merry#61]
I see this https://github.com/yoshuawuyts/merry/blob/master/index.js#L134 , but it doesn't look like it is called anywhere?

**Comment by yoshuawuyts** [comment]
oh yeah lol oops... ✨regression timeeee✨ - I'm currently working on other
stuff so this is not a priority for me; PR very welcome so this is booted
by default on start, has an option to disable and possiblyyyy a unit test
so we never ever forget about this again. But only if you have time and
feel like it, no pressure whatsoever. Thanks! :D

**Comment by yoshuawuyts** [comment]
Doneeeee
