### ISSUE TITLE
server example slightly biffed

### ISSUE THREAD

**Issue by cdaringe** [yoshuawuyts/merry#65]
# problem statement

- https://github.com/yoshuawuyts/merry#handler--appstart
  - `var server = http.createHttpServer()` :eyes:

# solution

- `var server = http.createServer(handler)`, i think?

didn't run the code, just casually reading :)

**Comment by lrlna** [comment]
@cdaringe woooooops! you're right, it should be `http.createServer(handler)` 🙊
If you want to PR this in, you're totally welcome ✨

**Comment by yoshuawuyts** [comment]
Fixed in 58d1e96 :sparkles: - thanks for reporting!
